[build]
  command = "pip install -r requirements.txt && streamlit run main.py --server.port 8501 --server.headless true"
  publish = "."

[build.environment]
  PYTHON_VERSION = "3.9"

[[redirects]]
  from = "/*"
  to = "/"
  status = 200